export const modules = [
  {
    id: 1,
    name: "Dashboard",
    description: "Visión general de la situación financiera de la empresa.",
    img: "dashboard-icon.png",
    link: "/dashboard",
    order: 1,
    activo: true,
    type: "Finanzas",
  },
  {
    id: 2,
    name: "Registro de Transacciones",
    description: "Permite registrar transacciones financieras.",
    img: "transaction-icon.png",
    link: "/transactions",
    order: 2,
    activo: true,
    type: "Finanzas",
  },
  {
    id: 3,
    name: "Cuentas por Pagar",
    description: "Gestiona las cuentas pendientes de pago a proveedores.",
    img: "payable-icon.png",
    link: "/payables",
    order: 3,
    activo: true,
    type: "Finanzas",
  },
  {
    id: 4,
    name: "Cuentas por Cobrar",
    description: "Gestiona las cuentas pendientes de cobro de clientes.",
    img: "receivable-icon.png",
    link: "/receivables",
    order: 4,
    activo: true,
    type: "Finanzas",
  },
  {
    id: 5,
    name: "Estado de Resultados",
    description: "Muestra el estado de resultados de la empresa.",
    img: "income-statement-icon.png",
    link: "/income-statement",
    order: 5,
    activo: true,
    type: "Finanzas",
  },
  {
    id: 6,
    name: "Balance General",
    description: "Muestra el balance general de la empresa.",
    img: "balance-sheet-icon.png",
    link: "/balance-sheet",
    order: 6,
    activo: true,
    type: "Finanzas",
  },
  {
    id: 7,
    name: "Informe de Flujo de Efectivo",
    description: "Muestra el flujo de efectivo de la empresa.",
    img: "cash-flow-icon.png",
    link: "/cash-flow",
    order: 7,
    activo: true,
    type: "Finanzas",
  },
  {
    id: 8,
    name: "Informe de Inventario",
    description: "Muestra información sobre el inventario.",
    img: "inventory-icon.png",
    link: "/inventory",
    order: 8,
    activo: true,
    type: "Inventario",
  },
  {
    id: 9,
    name: "Informes de Impuestos",
    description: "Muestra informes relacionados con impuestos.",
    img: "tax-report-icon.png",
    link: "/tax-reports",
    order: 9,
    activo: true,
    type: "Finanzas",
  },
  {
    id: 10,
    name: "Presupuesto vs. Realidad",
    description: "Compara presupuestos con resultados reales.",
    img: "budget-icon.png",
    link: "/budget-vs-actual",
    order: 10,
    activo: true,
    type: "Finanzas",
  },
  {
    id: 11,
    name: "Gestión de Usuarios y Roles",
    description: "Administra usuarios y roles en el sistema.",
    img: "user-management-icon.png",
    link: "/user-management",
    order: 11,
    activo: true,
    type: "Administración",
  },
  {
    id: 12,
    name: "Configuración y Preferencias",
    description: "Personaliza configuraciones y preferencias.",
    img: "settings-icon.png",
    link: "/settings",
    order: 12,
    activo: true,
    type: "Administración",
  },
  {
    id: 13,
    name: "Búsqueda y Filtros",
    description: "Permite buscar y filtrar información.",
    img: "search-icon.png",
    link: "/search",
    order: 13,
    activo: true,
    type: "Herramientas",
  },
  {
    id: 14,
    name: "Exportación de Datos",
    description: "Exporta datos en diferentes formatos.",
    img: "export-icon.png",
    link: "/export-data",
    order: 14,
    activo: true,
    type: "Herramientas",
  },
  {
    id: 15,
    name: "Ayuda y Soporte",
    description: "Acceso a recursos de ayuda y soporte técnico.",
    img: "help-icon.png",
    link: "/help",
    order: 15,
    activo: true,
    type: "Ayuda",
  },
  {
    id: 16,
    name: "Seguridad y Control de Acceso",
    description: "Gestión de seguridad y control de acceso.",
    img: "security-icon.png",
    link: "/security",
    order: 16,
    activo: true,
    type: "Seguridad",
  },
];
