import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Nav from "@/components/nav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={
          inter.className +
          "w-full transition-all ease-out overflow-auto lg:ml-0"
        }
      >
        <div className="flex flex-col relative h-screen">
          <Nav />
          <section className="w-full h-full overflow-y-auto bg-slate-100 dark:bg-gray-950 p-4 transition-colors">
            {children}
          </section>
        </div>
      </body>
    </html>
  );
}
